services:
    ayamel.mutate.transcode_log_listener:
        class: Ayamel\MutateBundle\TranscodeLogListener
        arguments: [@logger]
        tags:
            - { name: mutate.transcoder.listener }

    ayamel.mutate.filesystem_subscriber:
        class: Ayamel\MutateBundle\FilesystemSubscriber
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.filesystem.dispatcher.event_listener }