- hosts: all
  vars:
    production: false
  tasks:
    - include: common/tasks/sys.yml
    - include: common/tasks/install_mongodb.yml
      vars:
        small_files: true
    - include: common/tasks/install_symfony_reqs.yml
    - include: common/tasks/install_rabbitmq_server.yml
    - include: common/tasks/install_mediainfo.yml
    - include: common/tasks/install_elasticsearch.yml
    - include: common/tasks/create_swapfile.yml
      vars:
        swapsize: 512M
    #- include: common/tasks/install_ffmpeg.yml
    #- include: common/tasks/install_ffmpegthumbnailer.yml
    - copy:
        src: ../app/config/parameters.default.yml
        dest: /vagrant/app/config/parameters.yml
    - include: common/tasks/symfony_server.yml
      vars:
        name: ayamel-web-dev
        port: 80
        symfony_env: dev
        dir: /vagrant
    - file: src=/vagrant/app/console dest=/usr/local/bin/ayamel state=link
    - file: src=/vagrant dest=/home/vagrant/ayamel-server state=link
  handlers:
    - include: common/handlers/sys.yml
    - name: restart ayamel-web-dev
      supervisorctl: name=ayamel-web-dev state=restarted
    - name: restart rabbitmq-server
      supervisorctl: name=rabbitmq-server state=restarted
