- hosts: all
  vars:
    production: false
  tasks:
    - include: common/tasks/sys.yml
    - include: common/tasks/install_mongodb.yml
      vars:
        small_files: true
    - include: common/tasks/install_php5.yml
    - include: common/tasks/install_rabbitmq_server.yml
    - include: common/tasks/install_mediainfo.yml
    - include: common/tasks/install_elasticsearch.yml
    - include: common/tasks/create_swapfile.yml
      vars:
        swapsize: 512M
    #- include: common/tasks/install_ffmpeg.yml
    #- include: common/tasks/install_ffmpegthumbnailer.yml
    - copy:
        src: ../app/config/parameters.default.yml
        dest: /vagrant/app/config/parameters.yml
    - include: common/tasks/symfony_dev_server.yml
      vars:
        name: ayamel-web-dev
        dir: /vagrant
    - include: common/tasks/symfony_rabbitmq_consumer.yml
      vars:
        name: ayamel-rabbitmq-consumer-transcoding
        consumer: transcoding
        symfony_env: dev
        dir: /vagrant
        process_count: 4
    - include: common/tasks/symfony_rabbitmq_consumer.yml
      vars:
        name: ayamel-rabbitmq-consumer-search-index
        consumer: search_index
        symfony_env: dev
        dir: /vagrant
        process_count: 1
    - file: src=/vagrant dest=/home/vagrant/ayamel-server state=link
  handlers:
    - include: common/handlers/sys.yml
    - name: restart ayamel-web-dev
      supervisorctl: name=ayamel-web-dev state=restarted
    - name: restart ayamel-rabbitmq-consumer-transcoding
      ignore_errors: True
      supervisorctl: name='ayamel-rabbitmq-consumer-transcoding:' state=restarted
    - name: restart ayamel-rabbitmq-consumer-search-index
      ignore_errors: True
      supervisorctl: name='ayamel-rabbitmq-consumer-search-index:' state=restarted
