language: php

php:
    - 5.4
    - 5.5

env:
    - MONGO_VERSION=1.2.12

services:
    - mongodb
    - rabbitmq
    - elasticsearch

before_script:
    - sh -c "if [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ./tests/travis/php.ini ;fi"
    - composer self-update
    - phpenv config-add travis.php.ini
    - cp app/config/parameters.default.yml app/config/parameters.yml
    - sudo apt-get update -qq
    - sudo apt-get install -qq mediainfo 
#    - util/install_ffmpeg.sh
#    - sudo apt-get install -qq ffmpegthumbnailer
    - composer install --dev
    - app/console cache:clear --env=test

script: bin/phpunit --exclude-group=transcoding
