language: php

php:
    - 5.3
    - 5.4

env:
    - MONGO_VERSION=1.2.12

services:
    - mongodb
    - rabbitmq

before_script:
    - phpenv config-add travis.php.ini
    - composer install --dev
    - cp app/config/parameters.default.yml app/config/parameters.yml
    - app/console cache:clear --env=test