language: php

php:
    - 5.5
    - hhvm

services:
    - mongodb
    - rabbitmq
    - elasticsearch

before_script:
    - sh -c "if [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ./travis.php.ini ;fi"

    #attempt at hhvm support, config-add breaks using hhvm on travis for some reason
    #- phpenv config-add travis.php.ini
    - echo 'date.timezone = "America/New_York"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'apc.enabled = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'apc.cli_enabled = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - cp app/config/parameters.default.yml app/config/parameters.yml
    - sudo apt-get update -qq
    - sudo apt-get install -qq mediainfo 
#    - util/install_ffmpeg.sh
#    - sudo apt-get install -qq ffmpegthumbnailer
    - composer self-update
    - composer install --dev
    - app/console cache:clear --env=test

#memory limit seems to run out on some machines, setting it high to try and avoid
#unpredictable failures
script: bin/phpunit --exclude-group=transcoding -d memory_limit=512M
