language: php

php:
    - 5.5

services:
    - mongodb
    - rabbitmq
    - elasticsearch

before_script:
    - sh -c "if [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ./travis.php.ini ;fi"
    - phpenv config-add travis.php.ini
    - cp app/config/parameters.default.yml app/config/parameters.yml
    - sudo apt-get update -qq
    - sudo apt-get install -qq mediainfo 
#    - util/install_ffmpeg.sh
#    - sudo apt-get install -qq ffmpegthumbnailer
    - composer self-update
    - composer install --dev
    - app/console cache:clear --env=test

#memory limit seems to run out on some machines, setting it high to try and avoid
#unpredictable failures
script: bin/phpunit --exclude-group=transcoding -d memory_limit=512M
