language: php

php:
    - 5.3
    - 5.4

env:
    - MONGO_VERSION=1.2.12

services:
    - mongodb
    - rabbitmq

before_script:
    - phpenv config-add travis.php.ini
    - cp app/config/parameters.default.yml app/config/parameters.yml
    - sudo apt-get update -qq
    - sudo apt-get install -q mediainfo 
    - sudo ./util/install_ffmpeg.sh
    - sudo apt-get install -q ffmpegthumbnailer
    - composer install --dev
    - app/console cache:clear --env=test

#script: phpunit --exclude-group=transcoding
