client: default
#    persistence: 
#    settings:
types:
    resource:
        mappings:
            title: { boost: 5 }
            description: { boost: 3 }
            keywords: { boost: 3 }
            content: { boost: 2 }
