parameters:
    ayamel.search.language_field_map:
        # arabic
        ara: ['ar']
        # arabic
        arm: []
        # basque
        baq: []
        # brazilian portuguese
        brz: []
        # bulgarian
        bul: []
        # catalan
        cat: []
        # chinese
        zho: []
        # loosely defined asian scripts (chinese, japanese, korean, pin yin...)
        cjk: []
        # czech
        ces: []
        # danish
        dan: []
        # dutch
        dut: []
        # english
        eng: ['en']
        # finnish
        fin: []
        # french
        fra: []
        # galician
        glg: []
        # german
        deu: []
        # greek
        gre: []
        # hindi
        hin: []
        # hungarian
        hun: []
        # indonesian
        ind: []
        # italian
        ita: []
        # norwegian
        nor: []
        # persian
        fas: []
        # portuguese
        por: []
        # romanian
        ron: []
        # russian
        rus: ['ru']
        # spanish
        spa: []
        # swedish
        swe: []
        # turkish
        tur: []
        # thai
        tha: []
