parameters:
    ayamel.search.ayamel_index:
        client: default
        settings:
            index:
                analysis:
                    analyzer:
                        snow_en:
                            type: snowball
                            language: English
                        snow_ru:
                            type: snowball
                            language: Russian
                        # ... more of this for other languages

        types:
            resource:
                mappings:
                    title:
                        boost: 5
                        analyzer: default
                    description:
                        boost: 3
                        analyzer: default
                    keywords:
                        boost: 3
                        analyzer: default
                    content_canonical:
                        boost: 1
                        analyzer: default
                    content_eng:
                        boost: 2
                        analyzer: snow_en
                    content_ru:
                        boost: 2
                        analyzer: snow_ru
