imports:
    - { resource: "@AyamelSearchBundle/resources/config/config.ayamel_index.yml" }

parameters:
    ayamel.search.rabbitmq_producer:
        connection: default
        exchange_options: { name: 'search_index', type: direct }

    ayamel.search.rabbitmq_consumer:
        connection: default
        exchange_options: { name: 'search_index', type: direct }
        queue_options:    { name: 'search_index' }
        callback:         ayamel.search_index.consumer


services:
    ayamel.search_index.subscriber:
        class: Ayamel\SearchBundle\RabbitMQ\SearchIndexSubscriber
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.event_subscriber }

    # This service handles rabbitMQ for transcoding Resource files asyncronously
    ayamel.search_index.consumer:
        class: Ayamel\SearchBundle\RabbitMQ\SearchIndexConsumer
        arguments: [@service_container]

    ayamel.search.elastica_resource_provider:
        class: Ayamel\SearchBundle\Provider\ResourceProvider
        arguments: [@ayamel.search.resource_indexer, @fos_elastica.index.ayamel.resource]
        tags:
            - { name: fos_elastica.provider, index: ayamel, type: resource }

    ayamel.search.resource_indexer:
        class: Ayamel\SearchBundle\ResourceIndexer
