#browse the search index for resources w/ a simplified GET api
api_v1_search:
    pattern: /resources/search
    defaults: { _controller: Ayamel\SearchBundle\Controller\SearchV1::simpleSearchAction }
    requirements:
        _method:  GET

#pass-through POST api for elasticsearch
api_v1_advanced_search:
    pattern: /resources/search
    defaults: { _controller: Ayamel\SearchBundle\Controller\SearchV1::advancedSearchAction }
    requirements:
        _method:  POST
