parameters:
    ayamel.getid3.cache_dir: %kernel.cache_dir%/getid3
    
services:
	ayamel.getid3.filesystem_subscriber:
		class: Ayamel\GetID3Bundle\FilesystemSubscriber
		arguments: [@service_container, @ayamel.getid3.cache]
		tags: 
			- {name: ayamel.api.filesystem_subscriber}

    ayamel.getid3.cache:
        class: Ayamel\AyamelApiBundle\Cache\FileCache
        arguments: [%ayamel.getid3.cache_dir%]