imports:
    - { resource: '@AyamelResourceBundle/Resources/config/validation_map.yml' }

parameters:
    ayamel.resource.provider.type_extension_map:
        video: [mp4,m4v,wmv,mov,avi,webm]
        audio: [mp3,wma,m4a,aac,wav]
        image: [jpg,jpeg,gif,png,tiff]
        document: [txt,rtf,doc,docx,xls,xlsx,ppt,pptx,odt,ods,pdf,csv,html,htm,pages,numbers,key]
        archive: [zip,tar,rar,iso,gz,tz]
        data: [xml,json,csv,yml]

    ayamel.resource.provider.null_extension_type: data

    #this value describes which types of relations can be created for which types of subject Resources
    ayamel.relation.resource_type_map:
        audio: [search, based_on, references, version_of, part_of, translation_of]
        video: [search, based_on, references, version_of, part_of, translation_of]
        image: [search, based_on, references, version_of, part_of, translation_of]
        data: [search, part_of, based_on, version_of, translation_of, transcript_of, requires, references]
        collection: [search, contains, part_of, version_of, requires, references, based_on]
        document: [search, part_of, version_of, translation_of, transcript_of, requires, references]
        archive: [search, contains, part_of, version_of]

services:
    ayamel.resource.relation_attributes_validator:
        class: Ayamel\ResourceBundle\Validation\RelationAttributesValidator
        arguments: [@validator, %ayamel.resource.relation_attribute_validation_map%]
        tags:
            - { name: validator.constraint_validator, alias: relation_attributes_validator }

    ayamel.resource.file_attributes_validator:
        class: Ayamel\ResourceBundle\Validation\FileAttributesValidator
        arguments: [@validator, %ayamel.resource.file_attribute_validation_map%]
        tags:
          - { name: validator.constraint_validator, alias: file_attributes_validator }

    ayamel.resource.provider:
        class: Ayamel\ResourceBundle\Provider\DelegatingProvider

    ayamel.resource.local_provider:
        class: Ayamel\ResourceBundle\Provider\LocalFilepathProvider
        arguments: [%ayamel.resource.provider.type_extension_map%, %ayamel.resource.provider.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }

    ayamel.resource.http_provider:
        class: Ayamel\ResourceBundle\Provider\HttpProvider
        arguments: [%ayamel.resource.provider.type_extension_map%, %ayamel.resource.provider.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }
