parameters:
    ayamel.resource.types:
        mp4: video
        m4v: video
        wmv: video
        mov: video
        avi: video
        webm: video
        mp3: audio
        wma: audio
        m4a: audio
        aac: audio
        wav: audio
        jpg: image
        jpeg: image
        gif: image
        png: image
        tiff: image
        txt: document
        rtf: document
        doc: document
        docx: document
        xls: document
        xlsx: document
        ppt: document
        pptx: document
        odt: document
        pdf: document
        csv: document
        zip: archive
        tar: archive
        rar: archive
        iso: archive
        gz: archive
        tz: archive
        xml: data
        json: data
        csv: data
    ayamel.resource.null_extension_type: binary

    ayamel.resource.file_attribute_validation_map:
        Ayamel\ResourceBundle\Validation\File\VideoAttributes: 
            - video/mp4
            - video/x-ms-wmv
            - video/avi
        Ayamel\ResourceBundle\Validation\File\AudioAttributes: 
            - audio/mp3
            - audio/aac
        Ayamel\ResourceBundle\Validation\File\ImageAttributes: []
        Ayamel\ResourceBundle\Validation\File\DocumentAttributes: []
        Ayamel\ResourceBundle\Validation\File\DataAttributes: []

    ayamel.resource.relation_attribute_validation_map:
        PART_OF: Ayamel\ResourceBundle\Validation\Relation\PartOf
        REQUIRES: Ayamel\ResourceBundle\Validation\Relation\Requires
        DERIVED_FROM: Ayamel\ResourceBundle\Validation\Relation\DerivedFrom

services:
    ayamel.resource.file_validator:
        class: Ayamel\ResourceBundle\Validation\FileAttributes
        arguments: [@validator, %ayamel.resource.file_attribute_validation_map%]
        tags:
          - { name: validator.constraint_validator, alias: file_attributes }
          
    ayamel.resource.file_validator:
        class: Ayamel\ResourceBundle\Validation\FileAttributes
        arguments: [@validator, "getType", %ayamel.resource.file_attribute_validation_map%]
        tags:
          - { name: validator.constraint_validator, alias: file_attributes }

    ayamel.resource.provider:
        class: Ayamel\ResourceBundle\Provider\DelegatingProvider

    ayamel.resource.local_provider:
        class: Ayamel\ResourceBundle\Provider\LocalFilepathProvider
        arguments: [%ayamel.resource.types%, %ayamel.resource.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }

    ayamel.resource.ftp_provider:
        class: Ayamel\ResourceBundle\Provider\FtpProvider
        arguments: [%ayamel.resource.types%, %ayamel.resource.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }

    ayamel.resource.http_provider:
        class: Ayamel\ResourceBundle\Provider\HttpProvider
        arguments: [%ayamel.resource.types%, %ayamel.resource.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }
