parameters:
    ayamel.resource.types:
        mp4: video
        m4v: video
        wmv: video
        mov: video
        avi: video
        webm: video
        mp3: audio
        wma: audio
        m4a: audio
        aac: audio
        wav: audio
        jpg: image
        jpeg: image
        gif: image
        png: image
        tiff: image
        txt: document
        rtf: document
        doc: document
        docx: document
        xls: document
        xlsx: document
        ppt: document
        pptx: document
        odt: document
        pdf: document
        csv: document
        zip: archive
        tar: archive
        rar: archive
        iso: archive
        gz: archive
        tz: archive
        xml: data
        json: data
        csv: data
    ayamel.resource.null_extension_type: binary

services:
    ayamel.resource.provider:
        class: Ayamel\ResourceBundle\Provider\DelegatingProvider

    # Note that in order to load this service, a service for 'ayamel.resource.manager.backend' must be
    # configured.  This bundle does NOT provide that, it's up to your app, or another bundle to provide
    # the backend storage mechanism
    ayamel.resource.manager:
        class: Ayamel\ResourceBundle\Storage\ResourceManager
        arguments: [@ayamel.resource.manager.backend, @ayamel.resource.manager.dispatcher]

    ayamel.resource.manager.dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments: [@service_container]
        public: false

    ayamel.resource.local_provider:
        class: Ayamel\ResourceBundle\Provider\LocalFilepathProvider
        arguments: [%ayamel.resource.types%, %ayamel.resource.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }

    ayamel.resource.ftp_provider:
        class: Ayamel\ResourceBundle\Provider\FtpProvider
        arguments: [%ayamel.resource.types%, %ayamel.resource.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }

    ayamel.resource.http_provider:
        class: Ayamel\ResourceBundle\Provider\HttpProvider
        arguments: [%ayamel.resource.types%, %ayamel.resource.null_extension_type%]
        tags:
            - { name: ayamel.resource.provider_delegate }
