AyamelResourceBundle_homepage:
    pattern:  /
    defaults: { _controller: AyamelResourceBundle:Default:index }

#This uses the FOSRestBundle to define the api routes
AyamelResourceBundle_api_v1:
    type:  rest
    resource: Ayamel\ResourceBundle\Controller\ResourceApiV1Controller
