# This is the validation mapping for all Resource documents - only values that can be set by API clients are validated

Ayamel\ResourceBundle\Document\Resource:
    constraints:
        - Ayamel\ResourceBundle\Validation\ResourceSequenceConstraint: ~
    properties:
        title:
            - NotBlank: ~
            - Type:
                type: string
            - Length:
                max: 1000
        type:
            - NotBlank: ~
            - Type:
                type: string
            - Choice:
                choices: [video, audio, image, document, archive, collection, data]
        description:
            - Type:
                type: string
            - Length:
                max: 10000
        keywords:
            - Type:
                type: string
            - Length:
                max: 2000
        languages:
            - Valid: ~
        topics:
            - All:
                - Type:
                    type: string
                - Choice:
                    choices: ['arts', 'entertainment', 'culture', 'economy', 'education', 'food', 'geography', 'history', 'news', 'politics', 'religion', 'sports', 'technology', 'weather', 'other']
        formats:
            - All:
                - Type:
                    type: string
                - Choice:
                    choices: ['music', 'news', 'documentary', 'television', 'film', 'radio', 'skit', 'interview', 'role-play', 'presentation', 'home-conversation', 'public-interaction', 'grammar-lecture', 'cultural-lecture', 'how-to', 'other']
        authenticity:
            - All:
                - Type:
                    type: string
                - Choice:
                    choices: ['native', 'non-native', 'learner', 'other']
        registers:
            - All:
                - Type:
                    type: string
                - Choice:
                    choices: ['formal', 'casual', 'intimate', 'static', 'consultative', 'other']
        functions:
            - All:
                - Type:
                    type: string
                - Choice:
                    choices: ['explanation', 'request', 'response', 'persuasion', 'introduction', 'reporting', 'discussion', 'apology', 'invitation', 'promise', 'other']
        genres:
            - All:
                - Type:
                    type: string
                - Choice:
                    choices: ['comedy', 'drama', 'horror', 'history', 'romance', 'action', 'animation', 'children', 'classics', 'thriller', 'musical', 'science-fiction', 'fantasy', 'other']
        subjectDomains:
            - All:
                - Type:
                    type: string
#                - Choice:
#                    choices: []
        functionalDomains:
            - All:
                - Type:
                    type: string
#                - Choice:
#                    choices: []

        visibility:
            - All:
                - Type:
                    type: string
                - Length:
                    max: 100
        copyright:
            - Type:
                type: string
            - Length:
                max: 1000
        license:
            - Type:
                type: string
            - Length:
                max: 500
        origin:
            - Valid: ~
        client:
            - Valid: ~
        content:
            - Valid: ~
        clientUser:
            - Valid: ~

Ayamel\ResourceBundle\Document\Languages:
    #note that we aren't closely validating either - the lists of valid values are extremely large
    properties:
        iso639_3:
            - All:
                - Type:
                    type: string
                - Length:
                    min: 3
                    max: 3
        bcp47:
            - All:
                - Type:
                    type: string
                - Length:
                    min: 2
                    max: 12

Ayamel\ResourceBundle\Document\Origin:
    properties:
        creator:
            - Type:
                type: string
            - Length:
                max: 1000
        location:
            - Type:
                type: string
            - Length:
                max: 1000
        date:
            - Type:
                type: string
            - Length:
                max: 1000
        format:
            - Type:
                type: string
            - Length:
                max: 1000
        note:
            - Type:
                type: string
            - Length:
                max: 10000
        uri:
            - Url:
                protocols: [http, https, ftp, git, geo, nfs, irc, ircs, rtmp, svn, ws, wss]
            - Type:
                type: string
            - Length:
                max: 2500

Ayamel\ResourceBundle\Document\ClientUser:
    properties:
        id:
            - Type:
                type: string
            - Length:
                max: 1000
        url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2500

Ayamel\ResourceBundle\Document\ContentCollection:
    properties:
        canonicalUri:
            - Type:
                type: string
            - Length:
                max: 2500
        oembed:
            - Valid: ~
        files:
            - Valid:
                traverse: true

Ayamel\ResourceBundle\Document\OEmbed:
    properties:
        type:
            - NotBlank: ~
            - Choice:
                choices: [video, photo, link, rich]
        version:
            - Type:
                type: string
            - Length:
                max: 20
        title:
            - Type:
                type: string
            - Length:
                max: 1000
        author_name:
            - Type:
                type: string
            - Length:
                max: 1000
        author_url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2500
        provider_name:
            - Type:
                type: string
            - Length:
                max: 1000
        provider_url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2500
        cache_age:
            - Type:
                type: integer
            - Range:
                min: 0
        thumbnail_url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2000
        thumbnail_width:
            - Type:
                type: integer
            - Range:
                min: 0
        thumbnail_height:
            - Type:
                type: integer
            - Range:
                min: 0
        url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2000
        html:
            - Type:
                type: string
            - Length:
                max: 10000
        width:
            - Type:
                type: integer
            - Range:
                min: 0
        height:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Document\FileReference:
    constraints:
        - Ayamel\ResourceBundle\Validation\FileUriConstraint: ~
        - Ayamel\ResourceBundle\Validation\FileAttributesConstraint: ~
    properties:
        downloadUri:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2500
        streamUri:
            - Type:
                type: string
            - Length:
                max: 2500
        mime:
            - Type:
                type: string
            - Length:
                max: 2000
        mimeType:
            - NotBlank: ~
            - Type:
                type: string
            - Length:
                max: 100
        bytes:
            - Type:
                type: integer
            - Range:
                min: 0
        representation:
            - NotBlank: ~
            - Type:
                type: string
            - Choice:
                choices: [original, transcoding, summary]
        quality:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Document\Relation:
    constraints:
        - Ayamel\ResourceBundle\Validation\RelationAttributesConstraint: ~
    properties:
        clientUser:
            - Valid: ~
        subjectId:
            - NotBlank: ~
            - Type:
                type: string
        objectId:
            - NotBlank: ~
            - Type:
                type: string
        type:
            - NotBlank: ~
            - Choice:
                choices: [based_on, references, requires, transcript_of, search, version_of, part_of, translation_of, contains]

##
## FILE ATTRIBUTES
##

Ayamel\ResourceBundle\Validation\File\GenericVideoAttributes:
    properties:
        frameSize:
            - Collection:
                allowExtraFields: false
                allowMissingFields: false
                fields:
                    height:
                        - Type:
                            type: integer
                        - Range:
                            min: 0
                    width:
                        - Type:
                            type: integer
                        - Range:
                            min: 0
        duration:
            - Type:
                type: integer
            - Range:
                min: 0
        aspectRatio:
            - Type:
                type: string
            - Ayamel\ResourceBundle\Validation\AspectRatioConstraint: ~
        bitrate:
            - Type:
                type: integer
            - Range:
                min: 0
        frameRate:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Validation\File\GenericAudioAttributes:
    properties:
        duration:
            - Type:
                type: integer
            - Range:
                min: 0
        bitrate:
            - Type:
                type: integer
            - Range:
                min: 0
        channels:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Validation\File\GenericImageAttributes:
    properties:
        frameSize:
            - Collection:
                allowExtraFields: false
                allowMissingFields: false
                fields:
                    height:
                        - Type:
                            type: integer
                        - Range:
                            min: 0
                    width:
                        - Type:
                            type: integer
                        - Range:
                            min: 0
        aspectRatio:
            - Type:
                type: string
            - Ayamel\ResourceBundle\Validation\AspectRatioConstraint: ~
        time:
            - Type:
                type: integer
            - Range:
                min: 0
        units:
            - Type:
                type: string
            - Choice:
                choices: ['px', 'pt', 'em', 'pc', '%','ex', 'ch', 'rem', 'vw', 'vh', 'vmin', 'vmax', 'cm', 'mm', 'in']

Ayamel\ResourceBundle\Validation\File\GenericDocumentAttributes:
    properties:
        pages:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Validation\File\CaptionAttributes:
    properties:
        duration:
            - Type:
                type: integer
            - Range:
                min: 0

##
## RELATION ATTRIBUTES
##

Ayamel\ResourceBundle\Validation\Relation\PartOfAttributes:
    properties:
        index:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Validation\Relation\ContainsAttributes:
    properties:
        index:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Validation\Relation\VersionOfAttributes:
    properties:
        version:
            - Type:
                type: string
            - Length:
                max: 500

Ayamel\ResourceBundle\Validation\Relation\TranscriptOfAttributes:
    properties:
        kind:
            - Type:
                type: string
            - Choice:
                choices: ['subtitles', 'captions', 'descriptions', 'chapters', 'metadata']
