# This is the validation mapping for all Resource documents - only values that can be set by API clients are validated

Ayamel\ResourceBundle\Document\Resource:
    properties:
        title:
            - NotBlank: ~
            - Type: 
                type: string
            - Length: 
                max: 1000
        type:
            - NotBlank: ~
            - Type: 
                type: string
            - Choice:
                choices: [video, audio, image, document, archive, collection, data]
        description:
            - Type: 
                type: string
            - Length:
                max: 10000
        keywords:
            - Type:
                type: string
            - Length:
                max: 2000
        subjectDomains:
            - All:
                - Type:
                    type: string
#                - Choice:
#                    choices: []
        functionalDomains:
            - All:
                - Type:
                    type: string
#                - Choice:
#                    choices: []
        visibility:
            - All:
                - Type:
                    type: string
                - Length:
                    max: 100
        copyright:
            - Type:
                type: string
            - Length:
                max: 1000
        license:
            - Type:
                type: string
            - Length: 
                max: 500
        origin:
            - Valid: ~
        client:
            - Valid: ~
        content:
            - Valid: ~
        
Ayamel\ResourceBundle\Document\Origin:
    properties:
        creator:
            - Type: 
                type: string
            - Length:
                max: 1000
        location:
            - Type: 
                type: string
            - Length:
                max: 1000
        date:
            - Type: 
                type: string
            - Length:
                max: 1000
        format:
            - Type: 
                type: string
            - Length:
                max: 1000
        note:
            - Type: 
                type: string
            - Length:
                max: 10000
        uri:
            - Url:
                - protocols: [http, https, ftp, git, geo, nfs, irc, ircs, rtmp, svn, ws, wss]
            - Type: 
                type: string
            - Length:
                max: 2500

Ayamel\ResourceBundle\Document\Client:
    properties:
        user:
            - Valid: ~
            
Ayamel\ResourceBundle\Document\ClientUser:
    properties:
        id:
            - Type: 
                type: string
            - Length:
                max: 1000
        url:
            - Url: ~
            - Type: 
                type: string
            - Length:
                max: 2500

Ayamel\ResourceBundle\Document\ContentCollection:
    properties:
        canonicalUri:
            - Type: 
                type: string
            - Length:
                max: 2500
        oembed:
            - Valid: ~
        files:
            - All:
                - Valid: ~
            
Ayamel\ResourceBundle\Document\OEmbed:
    properties:
        type:
            - NotBlank: ~
            - Choice:
                choices: [video, photo, link, rich]
        version:
            - Type:
                type: string
            - Length:
                max: 20
        title:
            - Type:
                type: string
            - Length:
                max: 1000
        author_name:
            - Type:
                type: string
            - Length:
                max: 1000
        author_url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2500
        provider_name:
            - Type:
                type: string
            - Length:
                max: 1000
        provider_url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2500
        cache_age:
            - Type:
                type: integer
            - Range:
                min: 0
        thumbnail_url: 
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2000
        thumbnail_width: 
            - Type:
                type: integer
            - Range:
                min: 0
        thumbnail_height: 
            - Type:
                type: integer
            - Range:
                min: 0
        url:
            - Url: ~
            - Type:
                type: string
            - Length:
                max: 2000
        html: 
            - Type:
                type: string
            - Length:
                max: 10000
        width:
            - Type:
                type: integer
            - Range:
                min: 0
        height:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Document\FileReference:
    constraints:
        - Ayamel\ResourceBundle\Validation\FileAttributesConstraint: ~
    properties:
        downloadUri:
            - NotBlank: ~
            - Url: ~
            - Type: 
                type: string
            - Length:
                max: 2500
        streamUri:
            - Type: 
                type: string
            - Length:
                max: 2500
        mime:
            - Type:
                type: string
            - Length: 
                max: 2000
        mimeType:
            - NotBlank: ~
            - Type:
                type: string
            - Length: 
                max: 100
        bytes:
            - NotBlank: ~
            - Type:
                type: integer
            - Range:
                min: 0
        representation:
            - NotBlank: ~
            - Type:
                type: string
            - Choice:
                choices: [original, transcoding, summary]
        quality:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Document\Relation:
    constraints:
        Ayamel\ResourceBundle\Validation\RelationAttributesConstraint: ~
    properties:
        objectId:
            - NotBlank: ~
            - Type:
                type: string
        type:
            - NotBlank: ~
            - Choice:
                choices: [part_of, requires, depends_on]

##
## FILE ATTRIBUTES
##

Ayamel\ResourceBundle\Validation\File\VideoAttributes:
    properties:
        resolutionX:
            - Type: 
                type: integer
            - Range:
                min: 0
        resolutionY: 
            - Type: 
                type: integer
            - Range:
                min: 0
        duration: 
            - Type: 
                type: integer
            - Range:
                min: 0
        averageBitrate:
            - Type:
                type: integer
            - Range:
                min: 0

Ayamel\ResourceBundle\Validation\File\AudioAttributes:
    properties:
        duration: 
            - Type: 
                type: integer
            - Range:
                min: 0
        averageBitrate:
            - Type:
                type: integer
            - Range:
                min: 0

##
## RELATION ATTRIBUTES
##

Ayamel\ResourceBundle\Validation\Relation\PartOfAttributes:
    properties:
        index: 
            - Type:
                type: integer
            - Range:
                min: 0
        