imports:
#    - { resource: security.yml }
    - { resource: '@ACWebServicesBundle/Resources/config/config.yml' }
    - { resource: '@AyamelResourceBundle/Resources/config/config.yml' }
    - { resource: '@AyamelApiBundle/Resources/config/config.yml' }
    - { resource: '@AyamelFilesystemBundle/Resources/config/config.yml' }
    - { resource: '@ACTranscodingBundle/Resources/config/services.core.yml' }
#    - { resource: '@ACTranscodingBundle/Resources/config/services.ffmpeg.yml' }
    - { resource: '@ACTranscodingBundle/Resources/config/services.handbrake.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.preset_map.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.rabbitmq.yml' }
    # include parameters.yml last, git ignores it, so location specific overrides can go there safely
    - { resource: parameters.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: test_database
    document_managers:
        default:
            auto_mapping: true

## JMS Serializer, note that the actual serializer is a separate library finally
jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-dTH:i:s" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
    property_naming:
        separator:  
        lower_case: true
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true

nelmio_api_doc:
    name:   Ayamel Resource Library API
    sandbox:
        enabled:  true
        endpoint: /AyamelResourceApiServer/web/index_dev.php
#        authentication: # default null, if set, the value of the api key is read from the query string and appended to every sandbox api call
#            name: access_token
#            delivery: query # only query delivery is supported for now
