imports:
    - { resource: '@ACWebServicesBundle/Resources/config/config.yml' }
    - { resource: '@AyamelResourceBundle/Resources/config/config.yml' }
    - { resource: '@AyamelApiBundle/Resources/config/config.yml' }
    - { resource: '@AyamelFilesystemBundle/Resources/config/config.yml' }
    - { resource: '@ACTranscodingBundle/Resources/config/services.core.yml' }
#    - { resource: '@ACTranscodingBundle/Resources/config/services.ffmpeg.yml' }
    - { resource: '@ACTranscodingBundle/Resources/config/services.handbrake.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.preset_map.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.rabbitmq.yml' }
    - { resource: '@AyamelYouTubeBundle/Resources/config/config.yml' }

    # include parameters.yml last, git ignores it, so deployment specific overrides can go there safely
    - { resource: parameters.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enabled: true, enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

## JMS Serializer, note that the actual serializer is a separate library finally
jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-dTH:i:s" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
    property_naming:
        separator:  
        lower_case: true
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongodb_host%:%mongodb_port%
            options:
                connect: true
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true

ac_web_services:
    include_dev_exceptions: true
    include_response_data: true
    allow_code_suppression: true
    default_response_format: json
    api_paths: 
        - "/api/"

nelmio_api_doc:
    name:   Ayamel Media API Documentation
    sandbox:
        enabled:  true
        endpoint: %nelmio_api_doc_endpoint%
        authentication: # default null, if set, the value of the api key is read from the query string and appended to every sandbox api call
            name: _key
            delivery: query # only query delivery is supported for now

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
