imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

nelmio_api_doc:
    name:   Ayamel Media API Documentation
    sandbox:
        enabled:  true
        endpoint: /AyamelResourceApiServer/web/index_dev.php
        authentication: # default null, if set, the value of the api key is read from the query string and appended to every sandbox api call
            name: _key
            delivery: query # only query delivery is supported for now

services:
    # load api clients from config for testing
    ayamel.client_loader:
        class: Ayamel\ApiBundle\Client\ConfigClientLoader
        arguments: [%ayamel.clients%]

parameters:
    #test filesytem settings
    ayamel.filesystem.local_filesystem.root_dir: /tmp
    ayamel.filesystem.local_filesystem.secret: zeroisnotanumber
    
    # test api clients
    ayamel.clients:
        test_client:
            name: The Test Client
            apiKey: 45678isafgd56789asfgdhf4567
            #customPresets: {mime to preset map}
            #public: true/false
            #resourceDefaults: default license/copyright, etc...
        test_client2:
            name: Another Test Client
            apiKey: 55678isafgd56789asfgdhf4568
