imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

services:
    # register test text transcoding adapters/presets for testing
    ayamel.test.transcoding_adapter:
        class: AC\Transcoding\Tests\Mock\PhpTextAdapter
        tags:
            - { name: transcoding.adapter }
    ayamel.test.transcoding_preset:
        class: AC\Transcoding\Tests\Mock\TextToLowerCasePreset
        tags:
            - { name: transcoding.preset }
    
parameters:
    #transcode mapping for test
    ayamel.transcoding.preset_map:
        text/plain:
            - { preset: text_to_lower, tag: low, extension: txt, representation: transcoding, quality: 0 }
        
