imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: ayamel_test
    document_managers:
        default:
            auto_mapping: true

services:
    ayamel.test.transcoding_adapter:
        class: AC\Component\Transcoding\Tests\Mock\PhpTextAdapter
        tags:
            - { name: transcoding.adapter }
        
    ayamel.test.transcoding_preset:
        class: AC\Component\Transcoding\Tests\Mock\TextToLowerCasePreset
        tags:
            - { name: transcoding.preset }

parameters:
    #transcode mapping for test
    ayamel.transcoding.preset_map:
        text/plain:
            - { preset: text_to_lower, tag: low, extension: txt, representation: transcoding, quality: 0 }

    #filesytem settings
    ayamel.filesystem.local_filesystem.root_dir: /tmp
    ayamel.filesystem.local_filesystem.secret: zeroisnotanumber
    
    #TODO: custom rabbitmq settings (?)
