## Note that this parameters.yml file includes configuration for a test/dev environment.  For an
## actual production configuration, change this file accordingly.
parameters:
    mongodb_host: localhost
    mongodb_port: 27017
    mongodb_database: ayamel_%kernel.environment%

    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_vhost: '/'

    elasticsearch_index: ayamel_%kernel.environment%
    elasticsearch_host: 127.0.0.1
    elasticsearch_port: 9200
    search_index_queue_name: ayamel_search_index_%kernel.environment%

    #mailer_transport: smtp
    #mailer_host: localhost
    #mailer_user: null
    #mailer_password: null

    locale: en
    secret: thisisnotasafesecret

    apc_web_domain: http://127.0.0.1/AyamelResourceApiServer/web

    include_api_exception_data: true

    ## File upload handling ##
    filesystem_root_dir: %kernel.root_dir%/files/resource_uploads
    filesystem_secret: zeroisnotanumber
    filesystem_base_url: http://127.0.0.1/ayamel/web/files

    ## API Docs
    nelmio_api_doc_endpoint: http://127.0.0.1/AyamelResourceApiServer/web/app_dev.php

    ## Transcoding support
    transcoding_tmp_dir: %kernel.root_dir%/files/tmp
    ffmpeg_path: /usr/bin/ffmpeg
    ffmpegthumbnailer_path: /usr/bin/ffmpegthumbnailer
    transcoding_queue_name: ayamel_transcoding_%kernel.environment%
    #if you use ffmpeg w/ libvpx to encode webm, it doesn't seem to let you specify "-threads 0" to maximize cpu usage, instead
    #you have to be specific in the number of threads, which should be the same as the number of cores on the machine
    libvpx_threads: 4
    libx264_threads: 4

    ## media info ##
    mediainfo_path: /usr/bin/mediainfo
