## Note that this parameters.yml file includes configuration for a test/dev environment.  For an
## actual production configuration, change this file accordingly.
parameters:
    mongodb_host: localhost
    mongodb_port: 27017
    mongodb_database: ayamel_test

    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_vhost: '/'

    #mailer_transport: smtp
    #mailer_host: localhost
    #mailer_user: null
    #mailer_password: null

    locale: en
    secret: thisisnotasafesecret

    apc_web_domain: http://127.0.0.1/AyamelResourceApiServer/web


    ## File upload handling ##
    ayamel.filesystem.local_filesystem.root_dir: %kernel.root_dir%/files/resource_uploads
    ayamel.filesystem.local_filesystem.secret: zeroisnotanumber
    ayamel.filesystem.local_filesystem.base_uri: http://127.0.0.1/ayamel/web/files
    ayamel.transcoding.temp_directory: %kernel.root_dir%/files/tmp

    ## API Docs
    nelmio_api_doc_endpoint: http://127.0.0.1/AyamelResourceApiServer/web/index_dev.php

    ## Transcoding support
    ffmpeg_path: /usr/bin/ffmpeg
    handbrake_path: /usr/local/bin/HandBrakeCLI

    #if you use ffmpeg w/ libvpx to encode webm, it doesn't seem to let you specify "-threads 0" to maximize cpu usage, instead
    #you have to be specific in the number of threads, which should be the same as the number of cores on the machine
    libvpx_threads: 4

    ## media info ##
    mediainfo_path: /usr/bin/mediainfo
