parameters:
    database_driver: pdo_sqlite
    database_path: %kernel.root_dir%/app/data/db.sqlite
    database_host: localhost
    database_port: '9999'
    database_name: ayamel
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 1b577a9e247bf2c882bd861e1e825d83
    
    # Added by evan for local environment #
    
    ayamel.filesystem.local_filesystem.root_dir: /var/www/ayamel_api_file_uploads
    ayamel.filesystem.local_filesystem.secret: 34565dfg897jksksk4wk4ksdfkj34
    ayamel.filesystem.local_filesystem.base_uri: http://ayamel.americancouncils.org/files
    
    nelmio_api_doc.sandbox.endpoint: http://ayamel.americancouncils.org/index_dev.php
