parameters:
    database_driver: pdo_sqlite
    database_path: %kernel.root_dir%/app/data/db.sqlite
    database_host: localhost
    database_port: '9999'
    database_name: ayamel
    database_user: root
    database_password: null

    mongodb_host: localhost
    mongodb_port: 27017

    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_vhost: '/'

    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null

    locale: en
    secret: 1b577a9e247bf2c882bd861e1e825d83
    
    ## File upload handling ##
    ayamel.filesystem.local_filesystem.root_dir: %kernel.root_dir%/files/resource_uploads
    ayamel.filesystem.local_filesystem.secret: 34565dfg897jksksk4wk4ksdfkj34
    ayamel.filesystem.local_filesystem.base_uri: http://localhost/ayamel/web/files
    
    ## API Docs
    nelmio_api_doc.sandbox.endpoint: http://localhost/ayamel/web/index_dev.php

    ## Transcoding support
    transcoding.ffmpeg.path: /usr/bin/ffmpeg
    transcoding.handbrake.path: /usr/local/bin/HandBrakeCLI
    ayamel.transcoding.temp_directory: %kernel.root_dir%/files/tmp
    
