AyamelApiBundle:
    resource: "@AyamelApiBundle/Resources/config/routing.yml"

ApiDocs:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/docs
    
#SwaggerDocs:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.swagger.yml"
#    prefix: /api/v1/docs
