services:
    api_bootstrap_listener:
        class:        AC\WebServicesBundle\EventListener\ApiBootstrapListener
        arguments:    [@service_container]
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1000 }
