services:
    # can be used to create and/or modify objects annoted with JMSSerializerBundle annotations
    # from an incoming request
    ac.webservices.object_validator:
        class:      AC\WebServicesBundle\Util\ClientObjectValidator
        arguments:  [@jms_serializer.metadata_factory, @serializer, @ac.webservices.jms_parser, @validator]

    # responsible for instantiating the API request listeners for matching paths
    ac.webservices.request_listener:
        class:        AC\WebServicesBundle\EventListener\ApiBootstrapListener
        arguments:    [@service_container, %ac_web_services.api_paths%]
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1024 }

    #used internally in the object validator
    ac.webservices.jms_parser:
        class: AC\WebServicesBundle\Util\JmsDataTypeParser
        public: false
