# as the library grows, split the config into separate files as necessary
services:
	mutate.transcoder:
		class: AC\Mutate\Transcoder

	mutate.application:
		class: AC\Mutate\Application\Application
		
	#adapters provided with the library
	mutate.transcoder.adapter.phptext
		class: AC\Mutate\Adapter\PhpText
		tags:
			- {name: mutate.transcoder.adapter}
	
	#presets provided with the library
	mutate.transcoder.preset.strtolower
		class: AC\Mutate\Preset\TextToLowerCase
		tags:
			- {name: mutate.transcoder.preset}
	