parameters:
    mdcontent.root_dir: %kernel.root_dir%/markdown_content
    mdcontent.route_prefix: "content"
    mdcontent.default_template: "@ACMarkdownContentBundle:Default:page.html.twig"
    mdcontent.page_cache_lifetime: 600
    
services:
    mdcontent.cache:
        class: Whatever\Class
    mdcontent.route_loader:
        class: AC\MarkdownContentBundle\Routing\MarkdownContentRouteLoader
        arguments: [@mdcontent.cache, %mdcontent.root_dir%, %mdcontent.route_prefix%]
        tags:
            - { name: routing.loader }