parameters:
    ayamel.api.token_cache_dir: %kernel.cache_dir%/ayamel_upload_tokens

services:
    ayamel.api.client_data_validator:
        class: Ayamel\ResourceApiBundle\Validation\ClientResourceDataValidator

    ayamel.api.upload_token_manager:
        class: Ayamel\ResourceApiBundle\Validation\UploadTokenManager
        arguments: [@ayamel.api.token_cache]

    ayamel.api.token_cache:
        class: Ayamel\ResourceApiBundle\Cache\FileCache
        public: false
        arguments: [%ayamel.api.token_cache_dir%]

    ayamel.api.dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments: [@service_container]

    #provides the backend storage service for the resource manager in AyamelResourceBundle
    ayamel.resource.manager.backend:
        class: Ayamel\ResourceApiBundle\Storage\MongoResourceStorage
        arguments: [@doctrine.odm.mongodb.document_manager]
        
    ayamel.api.content.uri_subscriber:
        class: Ayamel\ResourceApiBundle\EventListener\UriContentSubscriber
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.dispatcher.event_subscriber }