parameters:
    ayamel.api.token_cache_dir: %kernel.cache_dir%/ayamel_upload_tokens
    ayamel.api.filesystem.root_dir: %kernel.root_dir%/files/ayamel_resource_uploads
    ayamel.api.filesystem.secret: 34565dfg897jksksk4wk4ksdfkj34

services:
    ayamel.api.client_data_validator:
        class: Ayamel\ResourceApiBundle\Validation\ClientResourceDataValidator

    ayamel.api.upload_token_manager:
        class: Ayamel\ResourceApiBundle\Validation\UploadTokenManager
        arguments: [@ayamel.api.token_cache]

    ayamel.api.token_cache:
        class: Ayamel\ResourceApiBundle\Cache\FileCache
        public: false
        arguments: [%ayamel.api.token_cache_dir%]

    ayamel.api.filesystem:
        class: Ayamel\ResourceApiBundle\Filesystem\LocalFilesystem
        arguments: [%ayamel.api.filesystem.root_dir%, %ayamel.api.filesystem.secret%]

    ayamel.api.dispatcher:
        class: Symfony\Bundle\FrameworkBundle\ContainerAwareEventDispatcher
        arguments: [@service_container]

    ayamel.api.filesystem_subscriber:
        class: Ayamel\ResourceApiBundle\EventListener\FilesystemSubscriber
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.dispatcher.event_subscriber }

    #provides the backend storage service for the resource manager in AyamelResourceBundle
    ayamel.resource.manager.backend:
        class: Ayamel\ResourceApiBundle\Storage\MongoResourceStorage
        arguments: [@doctrine.odm.mongodb.document_manager]