#AyamelResourceApiBundle_api_docs:
#    pattern: /tester

#AyamelResourceApiBundle_api_clients:
#    pattern: /{version}/clients

AyamelResourceApiBundle_home:
    pattern:   /
    defaults:  { _controller: Ayamel\ResourceApiBundle\Controller\ApiTester::indexAction }

AyamelResourceApiBundle_api_docs:
    pattern: /api/v1/docs
    defaults:  { _controller: Ayamel\ResourceApiBundle\Controller\ApiDocs::indexAction }

#version 1 of the api routes    
AyamelResourceApiBundle_api_v1:
    resource: "@AyamelResourceApiBundle/Resources/config/routing.api.v1.yml"
    prefix:   /api/v1/rest