parameters:
    ayamel.api.token_cache_dir: %kernel.cache_dir%/ayamel_upload_tokens
services:
    # validator service
    ayamel.api.client_data_validator:
        class: Ayamel\ResourceApiBundle\Validation\ClientResourceDataValidator
    ayamel.api.upload_token_manager:
        class: Ayamel\ResourceApiBundle\Validation\UploadTokenManager
        arguments: [@ayamel.api.token_cache]
    ayamel.api.token_cache:
        class: Ayamel\ResourceApiBundle\Cache\FileCache
        arguments: [%ayamel.api.token_cache_dir%]
#    ayamel.api.request_listener:
#todo