parameters:
    ayamel.transcoding.preset_map:
        video/mp4:
            - { preset: handbrake.ipod, tag: low, extension: mp4, representation: transcoding, quality: 1 }
            - { preset: handbrake.classic, tag: medium, extension: mp4, representation: transcoding, quality: 2 }
            - { preset: handbrake.high_profile, tag: high, extension: mp4, representation: transcoding, quality: 3 }
#            - { preset: ffmpeg.thumbnail, tag: thumb, extension: jpg, representation: transcoding, quality: 3, params: {} }
        video/quicktime:
            - { preset: handbrake.ipod, tag: low, extension: mp4, representation: transcoding, quality: 1 }
            - { preset: handbrake.classic, tag: medium, extension: mp4, representation: transcoding, quality: 2 }
            - { preset: handbrake.high_profile, tag: high, extension: mp4, representation: transcoding, quality: 3 }
#            - { preset: ffmpeg.thumbnail, tag: thumb, extension: jpg, representation: transcoding, quality: 3, params: {} }
        video/x-msvideo:
            - { preset: handbrake.ipod, tag: low, extension: mp4, representation: transcoding, quality: 1 }
            - { preset: handbrake.classic, tag: medium, extension: mp4, representation: transcoding, quality: 2 }
            - { preset: handbrake.high_profile, tag: high, extension: mp4, representation: transcoding, quality: 3 }
#            - { preset: ffmpeg.thumbnail, tag: thumb, extension: jpg, representation: transcoding, quality: 3, params: {} }
        video/x-ms-wmv:
            - { preset: handbrake.ipod, tag: low, extension: mp4, representation: transcoding, quality: 1 }
            - { preset: handbrake.classic, tag: medium, extension: mp4, representation: transcoding, quality: 2 }
            - { preset: handbrake.high_profile, tag: high, extension: mp4, representation: transcoding, quality: 3 }
#            - { preset: ffmpeg.thumbnail, tag: thumb, extension: jpg, representation: transcoding, quality: 3, params: {} }
        video/x-flv:
            - { preset: handbrake.ipod, tag: low, extension: mp4, representation: transcoding, quality: 1 }
            - { preset: handbrake.classic, tag: medium, extension: mp4, representation: transcoding, quality: 2 }
            - { preset: handbrake.high_profile, tag: high, extension: mp4, representation: transcoding, quality: 3 }
#            - { preset: ffmpeg.thumbnail, tag: thumb, extension: jpg, representation: transcoding, quality: 3, params: {} }
