parameters:
    ayamel.transcoding.presets:
##################################
## MP4
##################################
        video_to_mp4_low:
            preset_service: transcoding.preset.ffmpeg.generic_mp4
            tag: low
            quality: 1
            extension: mp4
            representation: transcoding
            params:
                "-s": 480x320
            #filters: no filters - the low quality preset should always apply, regardless of original video quality
        video_to_mp4_sd:
            preset_service: transcoding.preset.ffmpeg.generic_mp4
            tag: standard
            quality: 2
            extension: mp4
            representation: transcoding
            params:
                "-s": 640x480
            filters:
                height: 480
                width: 640
        video_to_mp4_hd:
            preset_service: transcoding.preset.ffmpeg.generic_mp4
            tag: high
            quality: 3
            extension: mp4
            representation: transcoding
            params:
                "-s": 1280x720
            filters:
                height: 720
                width: 1280
        video_to_mp4_full_hd:
            preset_service: transcoding.preset.ffmpeg.generic_mp4
            tag: highest
            quality: 4
            extension: mp4
            representation: transcoding
            params:
                "-s": 1920x1080
            filters:
                height: 1080
                width: 1920

##################################
## WEBM
##################################

        video_to_webm_low:
            preset_service: transcoding.preset.ffmpeg.generic_webm
            tag: low
            quality: 1
            extension: webm
            representation: transcoding
            params:
                "-s": 480x320
                "-threads": %libvpx_threads%
            #filters: no filters - the low quality preset should always apply, regardless of original video quality
        video_to_webm_sd:
            preset_service: transcoding.preset.ffmpeg.generic_webm
            tag: standard
            quality: 2
            extension: webm
            representation: transcoding
            params:
                "-s": 640x480
                "-threads": %libvpx_threads%
            filters:
                height: 480
                width: 640
        video_to_webm_hd:
            preset_service: transcoding.preset.ffmpeg.generic_webm
            tag: high
            quality: 3
            extension: webm
            representation: transcoding
            params:
                "-s": 1280x720
                "-threads": %libvpx_threads%
            filters:
                height: 720
                width: 1280
        video_to_webm_full_hd:
            preset_service: transcoding.preset.ffmpeg.generic_webm
            tag: highest
            quality: 4
            extension: webm
            representation: transcoding
            params:
                "-s": 1920x1080
                "-threads": %libvpx_threads%
            filters:
                height: 1080
                width: 1920

##################################
## VIDEO THUMBNAILS
##################################

        video_to_thumbnail:
            preset_service: transcoding.preset.ffmpeg.thumbnail
            tag: thumbnail_square_medium
            quality: 1
            extension: jpg
            representation: summary
            params:
                height: 100
                width: 100
                preserve_ratio: true
