parameters:
    ayamel.transcoding.preset_map:
        video/avi: [video_to_mp4_low, ]
        video/mp4: []
        video/webm: []
    ayamel.transcoding.presets:
##################################
## MP4
##################################
        video_to_mp4_low:   #mp4 480x320
            preset_service: transcoding.preset.ffmpeg.generic_mp4
            tag: low
            quality: 1
            extension: mp4
            representation: transcoding
            params:
                "-s": 480x320
            #filters: no filters - the low quality preset should always apply, regardless of original video quality
        video_to_mp4_standard:   #mp4 640x480
            preset_service: transcoding.preset.ffmpeg.generic_mp4
            tag: standard
            quality: 2
            extension: mp4
            representation: transcoding
            params:
                "-s": 640x480
            filters:
                height: 480
                width: 640
                