parameters:
    ayamel.transcoding.video_presets:
        - video_to_mp4_low
        - video_to_mp4_sd
        - video_to_mp4_hd
        - video_to_mp4_full_hd
        - video_to_webm_low
        - video_to_webm_sd
        - video_to_webm_hd
        - video_to_webm_full_hd
        - video_to_thumbnail

    #maps sets of presets to file mime types
    ayamel.transcoding.preset_map:
        #video
        video/mp4: %ayamel.transcoding.video_presets%
        video/x-ms-wmv: %ayamel.transcoding.video_presets%
        video/avi: %ayamel.transcoding.video_presets%
        video/msvideo: %ayamel.transcoding.video_presets%
        video/x-msvideo: %ayamel.transcoding.video_presets%
        video/avs-video: %ayamel.transcoding.video_presets%
        video/mpeg: %ayamel.transcoding.video_presets%
        video/x-motion-jpeg: %ayamel.transcoding.video_presets%
        video/x-mpeg: %ayamel.transcoding.video_presets%
        video/quicktime: %ayamel.transcoding.video_presets%
        video/webm: %ayamel.transcoding.video_presets%
        video/ogg: %ayamel.transcoding.video_presets%
        video/x-matroska: %ayamel.transcoding.video_presets%
        video/x-flv: %ayamel.transcoding.video_presets%

        #TODO: audio
        #TODO: image
        #TODO: documents
