parameters:
    ayamel.transcoding.temp_directory: %ayamel.filesystem.local_filesystem.root_dir%/tmp

services:
    ayamel.transcoding.mapper:
        class: Ayamel\TranscodingBundle\PresetMapper;
        arguments: [%ayamel.transcoding.preset_map%]
        scope: prototype
        
    # This service listens for file uploads, then registers a resource to have it's uploaded file
    # transcoded asyncronously
	ayamel.transcoding.publisher_listener:
        class: Ayamel\TranscodingBundle\RabbitMQ\PublisherListener
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.dispatcher.event_listener , event: ayamel.api.handle_uploaded_content, method: onHandleUploadedContent }

    # This service handles rabbitMQ for transcoding Resource files asyncronously
    ayamel.transcoding.consumer:
        class: Ayamel\TranscodingBundle\RabbitMQ\Consumer
        arguments: [@service_container, %ayamel.transcoding.preset_map%]
        