imports:
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.preset_map.yml' }
    - { resource: '@AyamelTranscodingBundle/Resources/config/config.rabbitmq.yml' }

parameters:
    ayamel.transcoding.temp_directory: %kernel.root_dir%/files/tmp

services:
    ayamel.transcoding.mapper:
        class: Ayamel\TranscodingBundle\PresetMapper
        arguments: [%ayamel.transcoding.preset_map%]
        scope: prototype

    ayamel.transcoding.manager:
        class: Ayamel\TranscodingBundle\TranscodeManager
        arguments:
            - @ayamel.api.filesystem
            - @doctrine.odm.mongodb.document_manager
            - @transcoder
            - %ayamel.transcoding.temp_directory%
            - @event_dispatcher
            - %ayamel.transcoding.preset_map%

    # This service listens for file uploads, then registers a resource to have it's uploaded file
    # transcoded asyncronously
    ayamel.transcoding.publisher_listener:
        class: Ayamel\TranscodingBundle\RabbitMQ\PublisherListener
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.dispatcher.event_listener , event: ayamel.api.handle_uploaded_content, method: onHandleUploadedContent, priority: 0 }

    # This service handles rabbitMQ for transcoding Resource files asyncronously
    ayamel.transcoding.consumer:
        class: Ayamel\TranscodingBundle\RabbitMQ\Consumer
        arguments: [@service_container, %ayamel.transcoding.preset_map%]
