parameters:
    ayamel.transcoding.presets:
##################################
## Video to MP4
##################################
        video_to_mp4_low:
            preset_service: transcoding.preset.ffmpeg_generic_mp4
            tag: low
            quality: 1
            extension: mp4
            representation: transcoding
            params:
                "-profile:v": "baseline"
                "-vf": "scale=trunc(oh*a/2)*2:360"
                "-b:v": "400k"
                "-maxrate": "500k"
                "-bufsize": "1000k"
                "-threads": %libx264_threads%
            #filters: none - the low quality preset should always apply, regardless of original video quality
        video_to_mp4_sd:
            preset_service: transcoding.preset.ffmpeg_generic_mp4
            tag: standard
            quality: 2
            extension: mp4
            representation: transcoding
            params:
                "-profile:v": "baseline"
                "-vf": "scale=trunc(oh*a/2)*2:480"
                "-b:v": "700k"
                "-maxrate": "900k"
                "-bufsize": "1800k"
                "-threads": %libx264_threads%
            filters:
                minHeight: 480
        video_to_mp4_hd:
            preset_service: transcoding.preset.ffmpeg_generic_mp4
            tag: high
            quality: 3
            extension: mp4
            representation: transcoding
            params:
                "-profile:v": "high"
                "-vf": "scale=trunc(oh*a/2)*2:720"
                "-b:v": "1500k"
                "-maxrate": "2000k"
                "-bufsize": "4000k"
                "-threads": %libx264_threads%
            filters:
                minHeight: 720
        video_to_mp4_full_hd:
            preset_service: transcoding.preset.ffmpeg_generic_mp4
            tag: highest
            quality: 4
            extension: mp4
            representation: transcoding
            params:
                "-profile:v": "high"
                "-vf": "scale=trunc(oh*a/2)*2:1080"
                "-b:v": "300k"
                "-maxrate": "4000k"
                "-bufsize": "8000k"
                "-threads": %libx264_threads%
            filters:
                minHeight: 1080

##################################
## Video to WEBM
##################################

        video_to_webm_low:
            preset_service: transcoding.preset.ffmpeg_generic_webm
            tag: low
            quality: 1
            extension: webm
            representation: transcoding
            params:
                "-b:v": "400k"
                "-maxrate": "500k"
                "-bufsize": "1000k"
                "-qmin": "10"
                "-qmax": "63"
                "-crf": "15"
                "-vf": "scale=trunc(oh*a/2)*2:360"
                "-threads": %libvpx_threads%
            #filters: no filters - the low quality preset should always apply, regardless of original video quality
        video_to_webm_sd:
            preset_service: transcoding.preset.ffmpeg_generic_webm
            tag: standard
            quality: 2
            extension: webm
            representation: transcoding
            params:
                "-b:v": "700k"
                "-maxrate": "900k"
                "-bufsize": "1800k"
                "-qmin": "10"
                "-qmax": "63"
                "-crf": "15"
                "-vf": "scale=trunc(oh*a/2)*2:480"
                "-threads": %libvpx_threads%
            filters:
                minHeight: 480
        video_to_webm_hd:
            preset_service: transcoding.preset.ffmpeg_generic_webm
            tag: high
            quality: 3
            extension: webm
            representation: transcoding
            params:
                "-b:v": "1500k"
                "-maxrate": "2000k"
                "-bufsize": "4000k"
                "-qmin": "5"
                "-qmax": "63"
                "-crf": "8"
                "-vf": "scale=trunc(oh*a/2)*2:720"
                "-threads": %libvpx_threads%
            filters:
                minHeight: 720
        video_to_webm_full_hd:
            preset_service: transcoding.preset.ffmpeg_generic_webm
            tag: highest
            quality: 4
            extension: webm
            representation: transcoding
            params:
                "-b:v": "3000k"
                "-maxrate": "4000k"
                "-bufsize": "8000k"
                "-qmin": "5"
                "-qmax": "63"
                "-crf": "8"
                "-vf": "scale=trunc(oh*a/2)*2:1080"
                "-threads": %libvpx_threads%
            filters:
                minHeight: 1080
