old_sound_rabbit_mq:
    connections:
        default:
            host:      %rabbitmq_host%
            port:      %rabbitmq_port%
            user:      %rabbitmq_user%
            password:  %rabbitmq_password%
            vhost:     %rabbitmq_vhost%

    producers:
        transcoding:
            connection: default
            exchange_options: { name: 'transcoding', type: direct }

    consumers:
        transcoding:
            connection: default
            exchange_options: { name: 'transcoding', type: direct }
            queue_options:    { name: 'transcoding' }
            callback:         ayamel.transcoding.consumer
