parameters:
    ayamel.api.token_cache_dir: %kernel.cache_dir%/ayamel_upload_tokens
    ayamel.api.client_data_validator.create_field_whitelist:
        resource:
            - title
            - type
            - description
            - public
            - relations
            - l2Data
            - copyright
            - keywords
            - categories
            - origin
            - client
            - restrictions
        

    ayamel.api.client_data_validator.update_field_whitelist:
        - title
        - type
        - description
        - public
        - relations
        - l2Data
        - copyright
        - keywords
        - categories
        - origin
        - client
        - restrictions
        
services:
    ayamel.api.client_data_validator:
        class: Ayamel\ApiBundle\Validation\ClientResourceDataValidator
        arguments: [%ayamel.api.client_data_validator.create_field_whitelist%, %ayamel.api.client_data_validator.update_field_whitelist%]

    ayamel.api.upload_token_manager:
        class: Ayamel\ApiBundle\Validation\UploadTokenManager
        arguments: [@ayamel.api.token_cache]

    ayamel.api.token_cache:
        class: Ayamel\ApiBundle\Cache\FileCache
        public: false
        arguments: [%ayamel.api.token_cache_dir%]

    ayamel.api.dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments: [@service_container]

    #provides the backend storage service for the resource manager in AyamelResourceBundle
    ayamel.resource.manager.backend:
        class: Ayamel\ApiBundle\Storage\MongoResourceStorage
        arguments: [@doctrine_mongodb.odm.document_manager]
        
    ayamel.api.content.uri_subscriber:
        class: Ayamel\ApiBundle\EventListener\UriContentSubscriber
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.dispatcher.event_subscriber }