parameters:
    ac.webservices.api_paths:
        - "/api/"
    ayamel.api.token_cache_dir: %kernel.cache_dir%/ayamel_upload_tokens

services:
    ayamel.api.upload_token_manager:
        class: Ayamel\ApiBundle\Validation\UploadTokenManager
        arguments: [@ayamel.api.token_cache]

    ayamel.api.token_cache:
        class: Ayamel\ApiBundle\Cache\FileCache
        public: false
        arguments: [%ayamel.api.token_cache_dir%]

    ayamel.api.dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments: [@service_container]

    #provides the backend storage service for the resource manager in AyamelResourceBundle
    ayamel.resource.manager.backend:
        class: Ayamel\ApiBundle\Storage\MongoResourceStorage
        arguments: [@doctrine_mongodb.odm.document_manager]

    ayamel.api.content.uri_subscriber:
        class: Ayamel\ApiBundle\EventListener\UriContentSubscriber
        arguments: [@service_container]
        tags:
            - { name: ayamel.api.dispatcher.event_subscriber }
