AyamelApiBundle_v1_get_resource:
    pattern:  /resources/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\GetResource::executeAction }
    requirements:
        _method:  GET

AyamelApiBundle_v1_modify_resource:
    pattern:  /resources/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\ModifyResource::executeAction }
    requirements:
        _method:  PUT

AyamelApiBundle_v1_create_resource:
    pattern: /resources
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\CreateResource::executeAction }
    requirements:
        _method:  POST
    
AyamelApiBundle_v1_remove_resource:
    pattern:  /resources/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RemoveResource::executeAction }
    requirements:
        _method:  DELETE

AyamelApiBundle_v1_request_content_upload:
    pattern: /resources/{id}/request-upload-url
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RequestContentUpload::executeAction }
    requirements:
        _method:  GET

AyamelApiBundle_v1_upload_content:
    pattern: /resources/{id}/content/{token}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\UploadContent::executeAction }
    requirements:
        _method:  POST
        
AyamelApiBundle_v1_scan_resource_uri:
    pattern: /resources/scan/{uri}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\ScanResourceUri::executeAction }
    requirements:
        _method:  GET

AyamelApiBundle_v1_search:
    pattern: /resources/search
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\Search::executeAction }
    requirements:
        _method:  GET

AyamelApiBundle_v1_player:
    pattern: /resources/{id}/player
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\EmbedPlayer::executeAction }
    requirements:
        _method:  GET

AyamelApiBundle_v1_oembed:
    pattern: /resources/oembed/{uri}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\OEmbedGenerator::executeAction }
    requirements:
        _method:  GET
        