#AyamelApiBundle_api_docs:
#    pattern: /{version}/docs

#AyamelApiBundle_api_clients:
#    pattern: /{version}/clients

AyamelApiBundle_home:
    pattern:   /
    defaults:  { _controller: Ayamel\ApiBundle\Controller\Homepage::indexAction }
    
AyamelApiBundle_api_v1:
    resource: "@AyamelApiBundle/Resources/config/routing.api.v1.yml"
    prefix:   /api/v1/rest