## Note that the order in which these routes are defined matters, don't rearrange them unless you know what you're doing ##

api_v1_get_resources:
    pattern: /resources
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\GetResources::executeAction }
    requirements:
        _method:  GET

#creates a new resource
api_v1_create_resource:
    pattern: /resources
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\CreateResource::executeAction }
    requirements:
        _method:  POST

#browse the search index for resources, note this doesn't returns summary resources, not full resource structures
api_v1_search:
    pattern: /resources/search
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\Search::searchForResources }
    requirements:
        _method:  GET

#create a resource object structure (no id), from a given uri (if it's something special like youtube, we'll connect to the api to fill in the relevant fields for you)
api_v1_scan_resource_uri:
    pattern: /resources/scan
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\ScanResourceUri::executeAction }
    requirements:
        _method:  GET

#get a specific resource by id
api_v1_get_resource:
    pattern:  /resources/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\GetResource::executeAction }
    requirements:
        _method:  GET

#modify a resource by id
api_v1_modify_resource:
    pattern:  /resources/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\ModifyResource::executeAction }
    requirements:
        _method:  PUT

#remove a resource by id
api_v1_delete_resource:
    pattern:  /resources/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\DeleteResource::executeAction }
    requirements:
        _method:  DELETE

#request a valid content upload url
api_v1_request_content_upload:
    pattern: /resources/{id}/request-upload-url
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RequestContentUpload::executeAction }
    requirements:
        _method:  GET

#upload content for a resource (could be a file, could be a string uri)
api_v1_upload_content:
    pattern: /resources/{id}/content/{token}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\UploadContent::executeAction }
    requirements:
        _method:  POST

#build an embeddable player for a given resource
api_v1_player:
    pattern: /resources/{id}/embed
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\EmbedPlayer::executeAction }
    requirements:
        _method:  GET

#filter relations
api_v1_filter_relations:
    pattern: /relations
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RelationsController::filterRelations }
    requirements:
        _method:  GET

#create a relation for a Resource
api_v1_create_relation:
    pattern: /relations
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RelationsController::createRelation }
    requirements:
        _method:  POST

#get relations for a resource, with ability to set various filters
api_v1_filter_resource_relations:
    pattern: /resources/{id}/relations
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RelationsController::filterResourceRelations }
    requirements:
        _method:  GET


#delete a specific relation for a resource
api_v1_delete_relation:
    pattern: /relations/{id}
    defaults: { _controller: Ayamel\ApiBundle\Controller\V1\RelationsController::deleteRelation }
    requirements:
        _method:  DELETE
