parameters:
    ayamel.clients:
        -
            id: flagship_media_library
            name: The Flagship Media Library
            keys:
                - 
                    key: 45678isafgd56789asfgdhf4567
                    ips: ~          #array of allowed ips
                    domains: ~      #array of allowed domains
        
            public: true    #whether or not information is queryable from the clients API
            resourceDefaults:
                license: CC BY-NC-SA 3.0
                copyright: 2013 The Language Learning Flagship
        
            
            #presets: for defining custom transcoding presets
        