services:
    ayamel.client_loader:
        class: Ayamel\ClientBundle\Loader\ConfigClientLoader
        arguments: [%ayamel.clients%]

parameters:
    ##client properties will be added to this over time
    ayamel.clients:
        -
            id: test_client
            name: The Test Client
            apiKey: 45678isafgd56789asfgdhf4567
            #customPresets: {mime to preset map}
            #public: true/false
            #resourceDefaults: default license/copyright, etc...